#!/bin/bash
set -e

mariadb -u root -p"$MARIADB_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${MATJIP_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${MATJIP_DB_USERNAME}'@'%' IDENTIFIED BY '${MATJIP_DB_PASSWORD}';
    GRANT ALL ON \`${MATJIP_DB_NAME}\`.* TO '${MATJIP_DB_USERNAME}'@'%';
    FLUSH PRIVILEGES;
EOSQL
